version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.10-stretch

    working_directory: /go/src/github.com/engineerd/kube-exec
    steps:
      - checkout

      - run: make dep
      - run: make build
      - run: make examples
