languageCode = "en-us"
title = "kube-exec"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true

# Enable Google Analytics by entering your tracking id
# googleAnalytics = ""

[params]
	# General information
	author = "Engineerd"

	description = "Lightweight Golang package for executing commands in remote Kubernetes pods"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/engineerd/kube-exec"

	#version = "1.0.0"
	#logo = "images/logo.png"
	favicon = ""

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue-grey"
    	accent  = "light-blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "engineerd"


[[menu.main]]
	name   = "Introduction"
	url    = "/introduction"
	weight = 1

[[menu.main]]
	name   = "Examples"
	url    = "/examples"
	weight = 3

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
